# Generated by Django 5.0.6 on 2024-07-09 20:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_subcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='colors',
        ),
        migrations.AddField(
            model_name='product',
            name='colors',
            field=models.CharField(default=datetime.datetime(2024, 7, 9, 20, 21, 29, 434516, tzinfo=datetime.timezone.utc), max_length=200),
            preserve_default=False,
        ),
    ]
